import { StyleSheet } from "react-native";
import { fonts } from "../../theme/typography";

export const responseModeToggleStyles = StyleSheet.create({
  container: {
    flexDirection: "row",
    gap: 6,
  },
  containerCompact: {
    flexDirection: "column",
    gap: 5,
  },
  option: {
    minHeight: 82,
    borderRadius: 12,
    borderWidth: 1,
    overflow: "hidden",
    alignSelf: "stretch",
  },
  optionRow: {
    flex: 1,
    minWidth: 0,
  },
  optionCompact: {
    minHeight: 54,
  },
  optionDetailedPortrait: {
    minHeight: 82,
  },
  optionCompactStack: {
    width: "100%",
    flexShrink: 0,
  },
  optionSingle: {
    minHeight: 80,
  },
  optionSingleCompact: {
    minHeight: 68,
  },
  optionDisabled: {
    opacity: 0.5,
  },
  optionPressed: {
    opacity: 0.82,
  },
  optionInner: {
    flex: 1,
    minHeight: 82,
    borderRadius: 11,
    paddingHorizontal: 9,
    paddingVertical: 9,
  },
  optionInnerCompact: {
    minHeight: 54,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  optionInnerDetailedPortrait: {
    minHeight: 82,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  optionInnerSingle: {
    minHeight: 80,
  },
  optionInnerSingleCompact: {
    minHeight: 68,
  },
  optionInnerThreeCardOneLine: {
    paddingVertical: 0,
  },
  optionContent: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  optionContentCompact: {
    flexDirection: "row",
  },
  optionContentDetailedPortrait: {
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 10,
  },
  optionContentDetailedPortraitSingle: {
    justifyContent: "flex-start",
  },
  optionContentThreeCardOneLine: {
    justifyContent: "space-evenly",
    gap: 0,
  },
  providerRow: {
    minHeight: 24,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  providerRowCompact: {
    width: 32,
    minHeight: 26,
    flexShrink: 0,
  },
  providerRowDetailedPortrait: {
    width: 40,
    minHeight: 34,
    flexShrink: 0,
  },
  providerRowDetailedPortraitSingle: {
    width: 48,
    minHeight: 42,
    flexShrink: 0,
  },
  providerRowThreeCardOneLine: {
    minHeight: 32,
  },
  modelTextSlot: {
    height: 30,
    width: "100%",
    justifyContent: "flex-start",
  },
  modelTextSlotCompact: {
    flex: 1,
    width: "auto",
    height: 30,
    justifyContent: "center",
  },
  modelTextSlotThreeCardOneLine: {
    height: 15,
    transform: [{ translateY: -2 }],
  },
  modelText: {
    fontSize: 12,
    lineHeight: 15,
    fontFamily: fonts.display,
    textAlign: "center",
  },
  modelTextCompact: {
    fontSize: 12,
    lineHeight: 15,
  },
  modelTextDensePortrait: {
    fontFamily: fonts.body,
    fontWeight: "400",
  },
  modelDetails: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 1,
  },
  modelDetailsSingle: {
    flex: 1,
    flexShrink: 1,
    maxWidth: 240,
    alignItems: "flex-start",
  },
  modelFamily: {
    fontSize: 10,
    lineHeight: 13,
    fontFamily: fonts.body,
    fontWeight: "600",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  modelFamilySingle: {
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 0.7,
  },
  modelTextDetailedPortrait: {
    width: "100%",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "left",
  },
  modelTextDetailedPortraitSingle: {
    width: "100%",
    maxWidth: "100%",
    fontSize: 16,
    lineHeight: 21,
    fontFamily: fonts.displayHeavy,
    textAlign: "left",
  },
  modelEffort: {
    fontSize: 10,
    lineHeight: 14,
    fontFamily: fonts.body,
  },
  modelEffortSingleSlot: {
    width: 80,
    flexShrink: 0,
    alignSelf: "stretch",
    marginLeft: 6,
    marginRight: 3,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  modelEffortSingleLabel: {
    fontSize: 9,
    lineHeight: 12,
    fontFamily: fonts.body,
    fontWeight: "500",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    maxWidth: "100%",
    textAlign: "right",
    opacity: 0.72,
  },
  modelEffortSingleValue: {
    fontSize: 11,
    lineHeight: 15,
    fontFamily: fonts.body,
    maxWidth: "100%",
    textAlign: "right",
    opacity: 0.78,
  },
  highlightedMetadata: {
    opacity: 0.82,
  },
  optionTrailingSpacerCompact: {
    width: 32,
    flexShrink: 0,
  },
  overflowSelector: {
    width: "100%",
    minHeight: 80,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    overflow: "hidden",
  },
  overflowSelectorCompact: {
    minHeight: 68,
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  overflowSelectorProvider: {
    width: 48,
    minHeight: 42,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  overflowSelectorProviderCompact: {
    width: 40,
    minHeight: 36,
  },
  overflowSelectorModel: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  overflowSelectorModelName: {
    width: "100%",
  },
  overflowSelectorModelNameCompact: {
    fontSize: 15,
    lineHeight: 20,
  },
  overflowSelectorEffort: {
    width: 56,
    flexShrink: 0,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  overflowSelectorEffortCompact: {
    width: 48,
  },
  overflowModalRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  overflowBackdrop: {
    ...StyleSheet.absoluteFill,
  },
  overflowSheetMotion: {
    width: "100%",
    maxWidth: 680,
    maxHeight: "78%",
    alignSelf: "center",
  },
  overflowSheetMotionCompact: {
    maxHeight: "88%",
  },
  overflowSheet: {
    width: "100%",
    flexShrink: 1,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    borderBottomWidth: 0,
    paddingTop: 8,
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 18,
    overflow: "hidden",
  },
  overflowSheetHandle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    alignSelf: "center",
    opacity: 0.72,
  },
  overflowSheetHeader: {
    minHeight: 70,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  overflowSheetHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  overflowSheetTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontFamily: fonts.displayHeavy,
  },
  overflowSheetSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: fonts.body,
  },
  overflowSheetClose: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  iconPressed: {
    opacity: 0.58,
    transform: [{ scale: 0.94 }],
  },
  overflowList: {
    flexGrow: 0,
    flexShrink: 1,
  },
  overflowListContent: {
    gap: 8,
    paddingHorizontal: 12,
    paddingBottom: 24,
  },
  overflowOption: {
    width: "100%",
    minHeight: 72,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  overflowOptionProvider: {
    width: 34,
    minHeight: 30,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  overflowOptionModel: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  overflowOptionProviderLabel: {
    fontSize: 9,
    lineHeight: 12,
    fontFamily: fonts.body,
    fontWeight: "600",
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  overflowOptionModelName: {
    fontSize: 14,
    lineHeight: 19,
    fontFamily: fonts.display,
  },
  overflowOptionEffort: {
    width: 68,
    flexShrink: 0,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  overflowOptionCheck: {
    width: 20,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
});
