import type { TranslationParams } from "./types";

type ImagePromptTranslation = {
  addImage: string;
  chooseImageSource: string;
  chooseFromPhotos: string;
  takePhoto: string;
  removeAttachedImage: (params: TranslationParams) => string;
  attachedImageLabel: (params: TranslationParams) => string;
  imageLimitReached: (params: TranslationParams) => string;
  cameraPermissionRequired: string;
  photoPermissionRequired: string;
  imageProcessingFailed: string;
  imageInputUnsupported: (params: TranslationParams) => string;
  imageProviderConsentTitle: string;
  imageProviderConsentMessage: (params: TranslationParams) => string;
  imageProviderConsentConfirm: string;
  conversationImagePlaceholder: (params: TranslationParams) => string;
};

export const imagePromptTranslations = {
  en: {
    addImage: "Add image",
    chooseImageSource: "Add an image",
    chooseFromPhotos: "Choose from photos",
    takePhoto: "Take a photo",
    removeAttachedImage: ({ index }) => `Remove attached image ${index}`,
    attachedImageLabel: ({ index, count }) => `Attached image ${index} of ${count}`,
    imageLimitReached: ({ count }) => `You can attach up to ${count} images.`,
    cameraPermissionRequired: "Camera access is needed to take a photo.",
    photoPermissionRequired: "Photo access is needed to choose an image.",
    imageProcessingFailed: "The image could not be prepared. Try another image.",
    imageInputUnsupported: ({ provider, model }) => `${provider} ${model} cannot use images. Choose an image-capable response mode.`,
    imageProviderConsentTitle: "Share images with these providers?",
    imageProviderConsentMessage: ({ providers }) => `This prompt or its conversation history contains images. Continuing sends them to: ${providers}.`,
    imageProviderConsentConfirm: "Share and continue",
    conversationImagePlaceholder: ({ count }) => count === 1 ? "[Image]" : `[${count} images]`,
  },
  de: {
    addImage: "Bild hinzufügen", chooseImageSource: "Bild hinzufügen", chooseFromPhotos: "Aus Fotos auswählen", takePhoto: "Foto aufnehmen",
    removeAttachedImage: ({ index }) => `Angehängtes Bild ${index} entfernen`, attachedImageLabel: ({ index, count }) => `Angehängtes Bild ${index} von ${count}`,
    imageLimitReached: ({ count }) => `Du kannst bis zu ${count} Bilder anhängen.`, cameraPermissionRequired: "Für ein Foto wird Kamerazugriff benötigt.", photoPermissionRequired: "Zum Auswählen eines Bildes wird Fotozugriff benötigt.",
    imageProcessingFailed: "Das Bild konnte nicht vorbereitet werden. Versuch es mit einem anderen Bild.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} kann keine Bilder verwenden. Wähle einen bildfähigen Antwortmodus.`,
    imageProviderConsentTitle: "Bilder mit diesen Anbietern teilen?", imageProviderConsentMessage: ({ providers }) => `Diese Anfrage oder ihr Gesprächsverlauf enthält Bilder. Wenn du fortfährst, werden sie gesendet an: ${providers}.`, imageProviderConsentConfirm: "Teilen und fortfahren",
    conversationImagePlaceholder: ({ count }) => count === 1 ? "[Bild]" : `[${count} Bilder]`,
  },
  uk: {
    addImage: "Додати зображення", chooseImageSource: "Додати зображення", chooseFromPhotos: "Вибрати з фотографій", takePhoto: "Зробити фото",
    removeAttachedImage: ({ index }) => `Видалити вкладене зображення ${index}`, attachedImageLabel: ({ index, count }) => `Вкладене зображення ${index} з ${count}`, imageLimitReached: ({ count }) => `Можна додати до ${count} зображень.`,
    cameraPermissionRequired: "Для зйомки потрібен доступ до камери.", photoPermissionRequired: "Для вибору зображення потрібен доступ до фотографій.", imageProcessingFailed: "Не вдалося підготувати зображення. Спробуйте інше.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} не підтримує зображення. Виберіть сумісний режим відповіді.`,
    imageProviderConsentTitle: "Поділитися зображеннями з цими провайдерами?", imageProviderConsentMessage: ({ providers }) => `Цей запит або історія розмови містить зображення. Якщо продовжити, їх буде надіслано таким провайдерам: ${providers}.`, imageProviderConsentConfirm: "Поділитися й продовжити", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Зображення]" : `[Зображення: ${count}]`,
  },
  hi: {
    addImage: "चित्र जोड़ें", chooseImageSource: "चित्र जोड़ें", chooseFromPhotos: "फ़ोटो से चुनें", takePhoto: "फ़ोटो लें", removeAttachedImage: ({ index }) => `संलग्न चित्र ${index} हटाएँ`, attachedImageLabel: ({ index, count }) => `संलग्न चित्र ${index}, कुल ${count}`, imageLimitReached: ({ count }) => `आप अधिकतम ${count} चित्र जोड़ सकते हैं।`, cameraPermissionRequired: "फ़ोटो लेने के लिए कैमरा अनुमति चाहिए।", photoPermissionRequired: "चित्र चुनने के लिए फ़ोटो अनुमति चाहिए।", imageProcessingFailed: "चित्र तैयार नहीं हो सका। कोई दूसरा चित्र आज़माएँ।", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} चित्रों का उपयोग नहीं कर सकता। चित्र-सक्षम उत्तर मोड चुनें।`, imageProviderConsentTitle: "इन प्रदाताओं से चित्र साझा करें?", imageProviderConsentMessage: ({ providers }) => `इस प्रॉम्प्ट या वार्तालाप इतिहास में चित्र हैं। जारी रखने पर वे यहाँ भेजे जाएँगे: ${providers}।`, imageProviderConsentConfirm: "साझा करके जारी रखें", conversationImagePlaceholder: ({ count }) => count === 1 ? "[चित्र]" : `[${count} चित्र]`,
  },
  es: {
    addImage: "Añadir imagen", chooseImageSource: "Añadir una imagen", chooseFromPhotos: "Elegir de Fotos", takePhoto: "Hacer una foto", removeAttachedImage: ({ index }) => `Eliminar imagen adjunta ${index}`, attachedImageLabel: ({ index, count }) => `Imagen adjunta ${index} de ${count}`, imageLimitReached: ({ count }) => `Puedes adjuntar hasta ${count} imágenes.`, cameraPermissionRequired: "Se necesita acceso a la cámara para hacer una foto.", photoPermissionRequired: "Se necesita acceso a Fotos para elegir una imagen.", imageProcessingFailed: "No se pudo preparar la imagen. Prueba con otra.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} no admite imágenes. Elige un modo de respuesta compatible.`, imageProviderConsentTitle: "¿Compartir imágenes con estos proveedores?", imageProviderConsentMessage: ({ providers }) => `Este mensaje o su historial contiene imágenes. Si continúas, se enviarán a: ${providers}.`, imageProviderConsentConfirm: "Compartir y continuar", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Imagen]" : `[${count} imágenes]`,
  },
  fr: {
    addImage: "Ajouter une image", chooseImageSource: "Ajouter une image", chooseFromPhotos: "Choisir dans Photos", takePhoto: "Prendre une photo", removeAttachedImage: ({ index }) => `Supprimer l’image jointe ${index}`, attachedImageLabel: ({ index, count }) => `Image jointe ${index} sur ${count}`, imageLimitReached: ({ count }) => `Vous pouvez joindre jusqu’à ${count} images.`, cameraPermissionRequired: "L’accès à l’appareil photo est requis.", photoPermissionRequired: "L’accès aux photos est requis pour choisir une image.", imageProcessingFailed: "L’image n’a pas pu être préparée. Essayez-en une autre.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} ne prend pas en charge les images. Choisissez un mode compatible.`, imageProviderConsentTitle: "Partager les images avec ces fournisseurs ?", imageProviderConsentMessage: ({ providers }) => `Ce message ou son historique contient des images. Continuer les enverra à : ${providers}.`, imageProviderConsentConfirm: "Partager et continuer", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Image]" : `[${count} images]`,
  },
  it: {
    addImage: "Aggiungi immagine", chooseImageSource: "Aggiungi un’immagine", chooseFromPhotos: "Scegli da Foto", takePhoto: "Scatta una foto", removeAttachedImage: ({ index }) => `Rimuovi immagine allegata ${index}`, attachedImageLabel: ({ index, count }) => `Immagine allegata ${index} di ${count}`, imageLimitReached: ({ count }) => `Puoi allegare fino a ${count} immagini.`, cameraPermissionRequired: "Serve l’accesso alla fotocamera per scattare una foto.", photoPermissionRequired: "Serve l’accesso alle foto per scegliere un’immagine.", imageProcessingFailed: "Impossibile preparare l’immagine. Provane un’altra.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} non supporta le immagini. Scegli una modalità compatibile.`, imageProviderConsentTitle: "Condividere le immagini con questi provider?", imageProviderConsentMessage: ({ providers }) => `Questo prompt o la cronologia contiene immagini. Continuando verranno inviate a: ${providers}.`, imageProviderConsentConfirm: "Condividi e continua", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Immagine]" : `[${count} immagini]`,
  },
  pt: {
    addImage: "Adicionar imagem", chooseImageSource: "Adicionar uma imagem", chooseFromPhotos: "Escolher das Fotos", takePhoto: "Tirar uma foto", removeAttachedImage: ({ index }) => `Remover imagem anexada ${index}`, attachedImageLabel: ({ index, count }) => `Imagem anexada ${index} de ${count}`, imageLimitReached: ({ count }) => `Pode anexar até ${count} imagens.`, cameraPermissionRequired: "É necessário acesso à câmara para tirar uma foto.", photoPermissionRequired: "É necessário acesso às fotos para escolher uma imagem.", imageProcessingFailed: "Não foi possível preparar a imagem. Tente outra.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} não suporta imagens. Escolha um modo compatível.`, imageProviderConsentTitle: "Partilhar imagens com estes fornecedores?", imageProviderConsentMessage: ({ providers }) => `Este pedido ou o histórico contém imagens. Ao continuar, serão enviadas para: ${providers}.`, imageProviderConsentConfirm: "Partilhar e continuar", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Imagem]" : `[${count} imagens]`,
  },
  ptBR: {
    addImage: "Adicionar imagem", chooseImageSource: "Adicionar uma imagem", chooseFromPhotos: "Escolher das Fotos", takePhoto: "Tirar uma foto", removeAttachedImage: ({ index }) => `Remover imagem anexada ${index}`, attachedImageLabel: ({ index, count }) => `Imagem anexada ${index} de ${count}`, imageLimitReached: ({ count }) => `Você pode anexar até ${count} imagens.`, cameraPermissionRequired: "É necessário acesso à câmera para tirar uma foto.", photoPermissionRequired: "É necessário acesso às fotos para escolher uma imagem.", imageProcessingFailed: "Não foi possível preparar a imagem. Tente outra.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} não aceita imagens. Escolha um modo compatível.`, imageProviderConsentTitle: "Compartilhar imagens com estes provedores?", imageProviderConsentMessage: ({ providers }) => `Este prompt ou o histórico contém imagens. Ao continuar, elas serão enviadas para: ${providers}.`, imageProviderConsentConfirm: "Compartilhar e continuar", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Imagem]" : `[${count} imagens]`,
  },
  ru: {
    addImage: "Добавить изображение", chooseImageSource: "Добавить изображение", chooseFromPhotos: "Выбрать из фото", takePhoto: "Сделать фото", removeAttachedImage: ({ index }) => `Удалить вложенное изображение ${index}`, attachedImageLabel: ({ index, count }) => `Вложенное изображение ${index} из ${count}`, imageLimitReached: ({ count }) => `Можно прикрепить до ${count} изображений.`, cameraPermissionRequired: "Для съёмки нужен доступ к камере.", photoPermissionRequired: "Для выбора изображения нужен доступ к фото.", imageProcessingFailed: "Не удалось подготовить изображение. Выберите другое.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} не поддерживает изображения. Выберите совместимый режим.`, imageProviderConsentTitle: "Отправить изображения этим провайдерам?", imageProviderConsentMessage: ({ providers }) => `Этот запрос или история диалога содержит изображения. При продолжении они будут отправлены: ${providers}.`, imageProviderConsentConfirm: "Отправить и продолжить", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Изображение]" : `[Изображения: ${count}]`,
  },
  zhCN: {
    addImage: "添加图片", chooseImageSource: "添加图片", chooseFromPhotos: "从照片中选择", takePhoto: "拍照", removeAttachedImage: ({ index }) => `移除附件图片 ${index}`, attachedImageLabel: ({ index, count }) => `附件图片 ${index}，共 ${count} 张`, imageLimitReached: ({ count }) => `最多可添加 ${count} 张图片。`, cameraPermissionRequired: "拍照需要相机权限。", photoPermissionRequired: "选择图片需要照片权限。", imageProcessingFailed: "无法处理该图片，请尝试其他图片。", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} 不支持图片。请选择支持图片的回复模式。`, imageProviderConsentTitle: "与这些提供商共享图片？", imageProviderConsentMessage: ({ providers }) => `此提示或对话历史包含图片。继续操作会将图片发送至：${providers}。`, imageProviderConsentConfirm: "共享并继续", conversationImagePlaceholder: ({ count }) => count === 1 ? "[图片]" : `[${count} 张图片]`,
  },
  ar: {
    addImage: "إضافة صورة", chooseImageSource: "إضافة صورة", chooseFromPhotos: "اختيار من الصور", takePhoto: "التقاط صورة", removeAttachedImage: ({ index }) => `إزالة الصورة المرفقة ${index}`, attachedImageLabel: ({ index, count }) => `الصورة المرفقة ${index} من ${count}`, imageLimitReached: ({ count }) => `يمكنك إرفاق ما يصل إلى ${count} صور.`, cameraPermissionRequired: "يلزم السماح بالكاميرا لالتقاط صورة.", photoPermissionRequired: "يلزم السماح بالصور لاختيار صورة.", imageProcessingFailed: "تعذر تجهيز الصورة. جرّب صورة أخرى.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} لا يدعم الصور. اختر وضع استجابة يدعم الصور.`, imageProviderConsentTitle: "مشاركة الصور مع هؤلاء المزوّدين؟", imageProviderConsentMessage: ({ providers }) => `يحتوي هذا الطلب أو سجل المحادثة على صور. ستُرسل عند المتابعة إلى: ${providers}.`, imageProviderConsentConfirm: "مشاركة ومتابعة", conversationImagePlaceholder: ({ count }) => count === 1 ? "[صورة]" : `[${count} صور]`,
  },
  ja: {
    addImage: "画像を追加", chooseImageSource: "画像を追加", chooseFromPhotos: "写真から選択", takePhoto: "写真を撮る", removeAttachedImage: ({ index }) => `添付画像 ${index} を削除`, attachedImageLabel: ({ index, count }) => `添付画像 ${index}/${count}`, imageLimitReached: ({ count }) => `画像は最大 ${count} 枚まで添付できます。`, cameraPermissionRequired: "撮影するにはカメラへのアクセスが必要です。", photoPermissionRequired: "画像を選ぶには写真へのアクセスが必要です。", imageProcessingFailed: "画像を準備できませんでした。別の画像をお試しください。", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} は画像に対応していません。対応する応答モードを選んでください。`, imageProviderConsentTitle: "これらのプロバイダーと画像を共有しますか？", imageProviderConsentMessage: ({ providers }) => `このプロンプトまたは会話履歴には画像が含まれます。続行すると次へ送信されます：${providers}。`, imageProviderConsentConfirm: "共有して続行", conversationImagePlaceholder: ({ count }) => count === 1 ? "[画像]" : `[画像 ${count} 枚]`,
  },
  hu: {
    addImage: "Kép hozzáadása", chooseImageSource: "Kép hozzáadása", chooseFromPhotos: "Választás a fotókból", takePhoto: "Fénykép készítése", removeAttachedImage: ({ index }) => `${index}. csatolt kép eltávolítása`, attachedImageLabel: ({ index, count }) => `${index}. csatolt kép, összesen ${count}`, imageLimitReached: ({ count }) => `Legfeljebb ${count} képet csatolhat.`, cameraPermissionRequired: "Fénykép készítéséhez kamera-hozzáférés szükséges.", photoPermissionRequired: "Kép kiválasztásához fotó-hozzáférés szükséges.", imageProcessingFailed: "A kép nem készíthető elő. Próbáljon másikat.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} nem támogat képeket. Válasszon képkezelésre alkalmas válaszmódot.`, imageProviderConsentTitle: "Megosztja a képeket ezekkel a szolgáltatókkal?", imageProviderConsentMessage: ({ providers }) => `A kérés vagy az előzmények képeket tartalmaznak. Folytatáskor ide kerülnek: ${providers}.`, imageProviderConsentConfirm: "Megosztás és folytatás", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Kép]" : `[${count} kép]`,
  },
  cs: {
    addImage: "Přidat obrázek", chooseImageSource: "Přidat obrázek", chooseFromPhotos: "Vybrat z fotek", takePhoto: "Pořídit fotku", removeAttachedImage: ({ index }) => `Odebrat přiložený obrázek ${index}`, attachedImageLabel: ({ index, count }) => `Přiložený obrázek ${index} z ${count}`, imageLimitReached: ({ count }) => `Můžete přiložit až ${count} obrázky.`, cameraPermissionRequired: "K pořízení fotky je potřeba přístup k fotoaparátu.", photoPermissionRequired: "K výběru obrázku je potřeba přístup k fotkám.", imageProcessingFailed: "Obrázek se nepodařilo připravit. Zkuste jiný.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} nepodporuje obrázky. Vyberte kompatibilní režim.`, imageProviderConsentTitle: "Sdílet obrázky s těmito poskytovateli?", imageProviderConsentMessage: ({ providers }) => `Tento dotaz nebo historie konverzace obsahuje obrázky. Pokračováním je odešlete těmto poskytovatelům: ${providers}.`, imageProviderConsentConfirm: "Sdílet a pokračovat", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Obrázek]" : `[${count} obrázky]`,
  },
  pl: {
    addImage: "Dodaj obraz", chooseImageSource: "Dodaj obraz", chooseFromPhotos: "Wybierz ze zdjęć", takePhoto: "Zrób zdjęcie", removeAttachedImage: ({ index }) => `Usuń załączony obraz ${index}`, attachedImageLabel: ({ index, count }) => `Załączony obraz ${index} z ${count}`, imageLimitReached: ({ count }) => `Możesz załączyć maksymalnie ${count} obrazy.`, cameraPermissionRequired: "Do zrobienia zdjęcia potrzebny jest dostęp do aparatu.", photoPermissionRequired: "Do wyboru obrazu potrzebny jest dostęp do zdjęć.", imageProcessingFailed: "Nie udało się przygotować obrazu. Spróbuj innego.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} nie obsługuje obrazów. Wybierz zgodny tryb odpowiedzi.`, imageProviderConsentTitle: "Udostępnić obrazy tym dostawcom?", imageProviderConsentMessage: ({ providers }) => `Ten monit lub historia rozmowy zawiera obrazy. Kontynuacja wyśle je do: ${providers}.`, imageProviderConsentConfirm: "Udostępnij i kontynuuj", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Obraz]" : `[${count} obrazy]`,
  },
  tr: {
    addImage: "Görsel ekle", chooseImageSource: "Görsel ekle", chooseFromPhotos: "Fotoğraflardan seç", takePhoto: "Fotoğraf çek", removeAttachedImage: ({ index }) => `${index}. ekli görseli kaldır`, attachedImageLabel: ({ index, count }) => `${count} ekli görselden ${index}.`, imageLimitReached: ({ count }) => `En fazla ${count} görsel ekleyebilirsiniz.`, cameraPermissionRequired: "Fotoğraf çekmek için kamera erişimi gerekir.", photoPermissionRequired: "Görsel seçmek için fotoğraf erişimi gerekir.", imageProcessingFailed: "Görsel hazırlanamadı. Başka bir görsel deneyin.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} görsel kullanamaz. Görsel destekleyen bir yanıt modu seçin.`, imageProviderConsentTitle: "Görseller bu sağlayıcılarla paylaşılsın mı?", imageProviderConsentMessage: ({ providers }) => `Bu istem veya konuşma geçmişi görsel içeriyor. Devam ederseniz şuraya gönderilir: ${providers}.`, imageProviderConsentConfirm: "Paylaş ve devam et", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Görsel]" : `[${count} görsel]`,
  },
  sv: {
    addImage: "Lägg till bild", chooseImageSource: "Lägg till en bild", chooseFromPhotos: "Välj från Bilder", takePhoto: "Ta ett foto", removeAttachedImage: ({ index }) => `Ta bort bifogad bild ${index}`, attachedImageLabel: ({ index, count }) => `Bifogad bild ${index} av ${count}`, imageLimitReached: ({ count }) => `Du kan bifoga upp till ${count} bilder.`, cameraPermissionRequired: "Kameraåtkomst krävs för att ta ett foto.", photoPermissionRequired: "Bildåtkomst krävs för att välja en bild.", imageProcessingFailed: "Bilden kunde inte förberedas. Prova en annan.", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} stöder inte bilder. Välj ett kompatibelt svarsläge.`, imageProviderConsentTitle: "Dela bilder med dessa leverantörer?", imageProviderConsentMessage: ({ providers }) => `Prompten eller samtalshistoriken innehåller bilder. Om du fortsätter skickas de till: ${providers}.`, imageProviderConsentConfirm: "Dela och fortsätt", conversationImagePlaceholder: ({ count }) => count === 1 ? "[Bild]" : `[${count} bilder]`,
  },
  ur: {
    addImage: "تصویر شامل کریں", chooseImageSource: "تصویر شامل کریں", chooseFromPhotos: "تصاویر میں سے منتخب کریں", takePhoto: "تصویر کھینچیں", removeAttachedImage: ({ index }) => `منسلک تصویر ${index} ہٹائیں`, attachedImageLabel: ({ index, count }) => `${count} میں سے منسلک تصویر ${index}`, imageLimitReached: ({ count }) => `آپ زیادہ سے زیادہ ${count} تصاویر شامل کر سکتے ہیں۔`, cameraPermissionRequired: "تصویر کھینچنے کے لیے کیمرے کی اجازت درکار ہے۔", photoPermissionRequired: "تصویر منتخب کرنے کے لیے تصاویر کی اجازت درکار ہے۔", imageProcessingFailed: "تصویر تیار نہیں ہو سکی۔ دوسری تصویر آزمائیں۔", imageInputUnsupported: ({ provider, model }) => `${provider} ${model} تصاویر استعمال نہیں کر سکتا۔ تصاویر والا جوابی موڈ منتخب کریں۔`, imageProviderConsentTitle: "ان فراہم کنندگان کے ساتھ تصاویر شیئر کریں؟", imageProviderConsentMessage: ({ providers }) => `اس پرامپٹ یا اس گفتگو کے سابقہ پیغامات میں تصاویر ہیں۔ جاری رکھنے پر انہیں یہاں بھیجا جائے گا: ${providers}۔`, imageProviderConsentConfirm: "شیئر کریں اور جاری رکھیں", conversationImagePlaceholder: ({ count }) => count === 1 ? "[تصویر]" : `[${count} تصاویر]`,
  },
} satisfies Record<string, ImagePromptTranslation>;
