import { sha256 } from "@noble/hashes/sha256";
import { bytesToHex, utf8ToBytes } from "@noble/hashes/utils";

import { getProviderLabel, getProviderModelName } from "../constants/models";
import type { Conversation, ConversationMeta, Message } from "../types";

export const CONVERSATION_ARCHIVE_SESSION_FILE_PATTERN =
  /^conversation-[a-f0-9]{64}\.md$/;

export interface ConversationArchiveRecord {
  conversation: Conversation;
  meta: ConversationMeta;
}

export interface ConversationArchiveDocuments {
  index: string;
  latest: string;
  sessions: Map<string, string>;
}

function yamlString(value: string) {
  return JSON.stringify(value);
}

function singleLine(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

function escapeMarkdownLinkLabel(value: string) {
  return singleLine(value).replace(/([\\\[\]])/g, "\\$1");
}

function formatAssistantLabel(message: Message) {
  if (message.provider && message.model) {
    return `${getProviderLabel(message.provider)} · ${getProviderModelName(
      message.provider,
      message.model,
    )}`;
  }
  if (message.provider) {
    return getProviderLabel(message.provider);
  }
  return message.model ?? "Assistant";
}

function formatMessageHeading(message: Message) {
  if (message.role === "user") {
    return "User";
  }
  const label = formatAssistantLabel(message);
  return label === "Assistant" ? label : `Assistant — ${label}`;
}

function formatMessageBody(message: Message) {
  const attachmentCount = message.attachments?.length ?? 0;
  const imagePlaceholder = attachmentCount
    ? `[${attachmentCount} ${attachmentCount === 1 ? "image" : "images"} attached]`
    : "";
  return [imagePlaceholder, message.content.trim()].filter(Boolean).join("\n\n");
}

function hasVisibleMessageContent(message: Message) {
  return message.content.trim().length > 0 || (message.attachments?.length ?? 0) > 0;
}

function formatTranscriptBody(conversation: Conversation) {
  return conversation.messages
    .filter(hasVisibleMessageContent)
    .map((message) =>
      [
        `## ${formatMessageHeading(message)}`,
        `_${message.timestamp}_`,
        formatMessageBody(message),
      ].join("\n\n"),
    )
    .join("\n\n");
}

export function getConversationArchiveFileName(conversationId: string) {
  const digest = bytesToHex(sha256(utf8ToBytes(conversationId)));
  return `conversation-${digest}.md`;
}

export function formatConversationArchiveDocument(
  record: ConversationArchiveRecord,
) {
  const { conversation, meta } = record;
  const title = singleLine(conversation.title) || "Untitled conversation";
  const body = formatTranscriptBody(conversation);
  const exportedMessageCount = conversation.messages.filter(
    hasVisibleMessageContent,
  ).length;

  return [
    "---",
    "format: mrbroccoli-conversation",
    "version: 1",
    `id: ${yamlString(conversation.id)}`,
    `title: ${yamlString(title)}`,
    `created_at: ${yamlString(conversation.createdAt)}`,
    `updated_at: ${yamlString(conversation.updatedAt)}`,
    `pinned: ${meta.pinned}`,
    `message_count: ${exportedMessageCount}`,
    "---",
    "",
    "<!-- Generated by Mr Broccoli. Local edits to this file are overwritten. -->",
    "",
    `# ${title}`,
    body ? `\n${body}` : "",
    "",
  ].join("\n");
}

export function formatConversationForAiHandoff(conversation: Conversation) {
  const title = singleLine(conversation.title) || "Untitled conversation";
  const body = formatTranscriptBody(conversation);

  return [
    `# Conversation handoff: ${title}`,
    "",
    "Use this transcript as context and continue from its final turn.",
    body ? `\n${body}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

function compareRecords(
  left: ConversationArchiveRecord,
  right: ConversationArchiveRecord,
) {
  if (left.meta.pinned !== right.meta.pinned) {
    return left.meta.pinned ? -1 : 1;
  }
  return right.conversation.updatedAt.localeCompare(
    left.conversation.updatedAt,
  );
}

export function buildConversationArchiveDocuments(params: {
  activeConversationId: string | null;
  exportedAt: string;
  records: ConversationArchiveRecord[];
}): ConversationArchiveDocuments {
  const records = [...params.records].sort(compareRecords);
  const sessions = new Map<string, string>();

  for (const record of records) {
    sessions.set(
      getConversationArchiveFileName(record.conversation.id),
      formatConversationArchiveDocument(record),
    );
  }

  const latestRecord =
    records.find(
      (record) => record.conversation.id === params.activeConversationId,
    ) ??
    [...records].sort((left, right) =>
      right.conversation.updatedAt.localeCompare(left.conversation.updatedAt),
    )[0];
  const indexRows = records.map((record) => {
    const title =
      escapeMarkdownLinkLabel(record.conversation.title) ||
      "Untitled conversation";
    const pin = record.meta.pinned ? " · pinned" : "";
    return `- [${title}](sessions/${getConversationArchiveFileName(
      record.conversation.id,
    )}) — ${record.conversation.updatedAt}${pin}`;
  });
  const index = [
    "---",
    "format: mrbroccoli-conversation-index",
    "version: 1",
    `exported_at: ${yamlString(params.exportedAt)}`,
    `conversation_count: ${records.length}`,
    "---",
    "",
    "<!-- Generated by Mr Broccoli. Local edits to this file are overwritten. -->",
    "",
    "# Mr Broccoli conversations",
    "",
    ...(indexRows.length > 0 ? indexRows : ["No conversations yet."]),
    "",
  ].join("\n");
  const latest = latestRecord
    ? formatConversationArchiveDocument(latestRecord)
    : [
        "---",
        "format: mrbroccoli-conversation",
        "version: 1",
        "message_count: 0",
        "---",
        "",
        "# No conversations yet",
        "",
      ].join("\n");

  return { index, latest, sessions };
}
