import { StyleSheet } from "react-native";

import { fonts } from "../../theme/typography";

const PORTRAIT_HORIZONTAL_GUTTER = 16;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  orb: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    opacity: 0.8,
  },
  orbTop: {
    top: -60,
    right: -90,
  },
  orbBottom: {
    bottom: 90,
    left: -80,
  },
  defaultLayout: {
    flex: 1,
    paddingHorizontal: PORTRAIT_HORIZONTAL_GUTTER,
    paddingBottom: 10,
  },
  defaultLayoutLandscape: {
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  defaultScroll: {
    flex: 1,
  },
  defaultLayoutContent: {
    paddingBottom: 28,
  },
  workspaceBody: {
    flex: 1,
    minHeight: 0,
    gap: 6,
  },
  workspaceTranscript: {
    flex: 1,
    minHeight: 0,
  },
  portraitConversationStack: {
    flex: 1,
    minHeight: 0,
    gap: 10,
    marginTop: 6,
  },
  portraitTranscriptPane: {
    flex: 1,
    minHeight: 0,
  },
  landscapeShell: {
    flex: 1,
    flexDirection: "row",
    alignItems: "stretch",
    minHeight: 0,
  },
  landscapeLeftColumn: {
    flex: 0.42,
    minWidth: 0,
    paddingRight: 12,
  },
  landscapeRightColumn: {
    flex: 1,
    minWidth: 0,
    paddingLeft: 12,
  },
  landscapePaneDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: "stretch",
  },
  landscapeStageArea: {
    flex: 1,
    minHeight: 0,
    justifyContent: "flex-end",
    alignItems: "stretch",
    gap: 8,
    paddingVertical: 8,
  },
  landscapeTranscriptCard: {
    flex: 1,
    minHeight: 0,
  },
  heroCard: {
    padding: 0,
    marginBottom: 0,
  },
  heroCardLandscape: {
    marginBottom: 0,
  },
  heroCardGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  routeModeRow: {
    width: "100%",
  },
  providerEmptyState: {
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 96,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: "center",
    gap: 6,
  },
  providerEmptyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  providerEmptyBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  providerEmptyBadgeText: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  providerEmptyTitle: {
    fontSize: 14,
    fontFamily: fonts.display,
  },
  providerEmptyText: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  eyebrow: {
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  livePill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 8,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  livePillText: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  stageBlock: {
    width: "100%",
    paddingTop: 0,
    paddingBottom: 0,
  },
  stageBlockLandscape: {
    paddingTop: 0,
    paddingBottom: 0,
  },
  transcriptShell: {
    flex: 1,
    minHeight: 0,
    borderRadius: 16,
    borderWidth: 1,
    position: "relative",
    overflow: "hidden",
    paddingTop: 0,
    shadowOpacity: 0,
  },
  transcriptShellCanvas: {
    flex: 1,
    minHeight: 0,
    borderRadius: 0,
    borderWidth: 0,
  },
  transcriptShellPortraitCanvas: {
    overflow: "visible",
  },
  transcriptHeader: {
    minHeight: 52,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 2,
  },
  transcriptHeaderPortraitCanvas: {
    marginHorizontal: -PORTRAIT_HORIZONTAL_GUTTER,
    borderTopWidth: 1,
  },
  transcriptHeaderCopy: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  transcriptHeaderControls: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    marginLeft: 8,
    gap: 4,
  },
  transcriptStyleControl: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  transcriptTitle: {
    width: "100%",
    fontSize: 15,
    lineHeight: 20,
    fontFamily: fonts.display,
  },
  transcriptBody: {
    flex: 1,
    minHeight: 0,
  },
  menuIconButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  previewTranscriptContent: {
    paddingTop: 8,
    paddingHorizontal: 4,
    paddingBottom: 18,
  },
  voiceDock: {
    borderRadius: 0,
    borderWidth: 0,
    padding: 0,
    gap: 8,
    shadowOpacity: 0,
    elevation: 0,
  },
  statusDetailsOverlay: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    backgroundColor: "rgba(0,0,0,0.16)",
  },
  statusDetailsCard: {
    width: "100%",
    alignSelf: "center",
    borderRadius: 16,
    borderWidth: 1,
    padding: 20,
    gap: 16,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 12,
  },
  statusDetailsHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  statusDetailsHeaderCopy: {
    flex: 1,
    gap: 6,
  },
  statusDetailsTitle: {
    fontSize: 24,
    lineHeight: 28,
    fontFamily: fonts.display,
  },
  statusDetailsSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  statusDetailsBadges: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
  },
  statusDetailsBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statusDetailsBadgeText: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  statusDetailsList: {
    gap: 10,
  },
  statusDetailsItem: {
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  statusDetailsItemLabel: {
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  styleSheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.16)",
  },
  styleSheetCard: {
    width: "100%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderBottomWidth: 0,
    overflow: "hidden",
    shadowOffset: { width: 0, height: -12 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 12,
  },
  styleSheetScroll: {
    flexShrink: 1,
  },
  styleSheetScrollContent: {
    gap: 18,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 20,
  },
  styleSheetScrollContentLandscape: {
    gap: 12,
    paddingTop: 12,
    paddingBottom: 14,
  },
  styleSheetHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  styleSheetHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  styleSheetCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  styleSheetTitle: {
    fontSize: 22,
    lineHeight: 26,
    fontFamily: fonts.display,
  },
  styleSheetSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  styleSheetGroup: {
    gap: 8,
  },
  styleSheetGroupLandscape: {
    flex: 1,
    minWidth: 0,
  },
  styleSheetOptionsColumn: {
    gap: 18,
  },
  styleSheetOptionsRowLandscape: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
  },
  styleSheetInstructionRowLandscape: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 16,
  },
  styleSheetGroupLabel: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  styleSheetPillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  styleSheetPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  styleSheetPillText: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  styleSheetDescription: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
    paddingHorizontal: 4,
  },
  styleSheetInstructionInput: {
    minHeight: 88,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  styleSheetVoicePicker: {
    marginBottom: 0,
  },
  styleSheetAutoRenameButton: {
    minHeight: 38,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  styleSheetAutoRenameButtonText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: fonts.display,
  },
  styleSheetFooter: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
    borderTopWidth: 1,
  },
  styleSheetDoneButton: {
    alignSelf: "stretch",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  styleSheetDoneButtonText: {
    fontSize: 14,
    fontFamily: fonts.display,
  },
});
