import type { Colors } from "../theme/colors";

export function createAntTheme(colors: Colors) {
  return {
    color_text_base: colors.text,
    color_text_base_inverse: colors.onActiveControl,
    color_text_placeholder: colors.textMuted,
    color_text_disabled: colors.textMuted,
    color_text_caption: colors.textSecondary,
    color_text_paragraph: colors.text,
    color_link: colors.accent,
    color_icon_base: colors.textSecondary,
    fill_body: colors.background,
    fill_base: colors.surface,
    fill_tap: colors.accentSoft,
    fill_disabled: colors.surfaceAlt,
    fill_mask: colors.overlay,
    fill_grey: colors.surfaceAlt,
    brand_primary: colors.accent,
    brand_primary_tap: colors.activeControl,
    brand_success: colors.success,
    brand_warning: colors.phaseSynthesizing,
    brand_error: colors.danger,
    brand_important: colors.danger,
    border_color_base: colors.border,
    border_color_thin: colors.inactiveControlBorder,
    primary_button_fill: colors.activeControl,
    primary_button_fill_tap: colors.accent,
    ghost_button_color: colors.accent,
    ghost_button_fill_tap: colors.accentSoft,
    warning_button_fill: colors.dangerFill,
    warning_button_fill_tap: colors.danger,
    checkbox_border: colors.borderStrong,
    checkbox_border_disabled: colors.border,
    switch_unchecked: colors.borderStrong,
    switch_unchecked_disabled: colors.border,
    tab_bar_fill: colors.surface,
    search_bar_fill: colors.surfaceAlt,
    search_color_icon: colors.textMuted,
    toast_fill: colors.text,
    tooltip_dark: colors.text,
    radius_xs: 6,
    radius_sm: 8,
    radius_md: 12,
    radius_lg: 16,
  };
}
