#!/usr/bin/env python3

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PROVIDERS_DIR = REPO_ROOT / "data" / "providers"
INDEX_PATH = PROVIDERS_DIR / "index.ts"
CATALOG_UPDATED_AT = "2026-07-24"


def to_identifier(slug: str) -> str:
    parts = [part for part in slug.replace(".", "-").split("-") if part]
    identifier = "".join(part[:1].upper() + part[1:] for part in parts)

    if identifier[:1].isdigit():
        identifier = "Provider" + identifier

    return identifier + "Document"


def list_provider_entries() -> list[str]:
    entries: list[str] = []

    for path in sorted(PROVIDERS_DIR.iterdir()):
        if path.name.startswith(".") or path.name in {"index.ts", "definitions.ts"}:
            continue

        if path.is_dir():
            if (path / "index.ts").exists():
                entries.append(path.name)
            continue

        if path.suffix == ".ts":
            entries.append(path.stem)

    return entries


def render_index(entries: list[str]) -> str:
    import_lines = [
        f'import {to_identifier(entry)} from "./{entry}";' for entry in entries
    ]
    value_lines = [f"  {to_identifier(entry)}," for entry in entries]

    return "\n".join(
        [
            "// Generated by scripts/provider_catalog/generate_provider_index.py",
            "",
            'import { defineProviderDocuments } from "./definitions";',
            "",
            *import_lines,
            "",
            "export const PROVIDER_DOCUMENTS = defineProviderDocuments([",
            *value_lines,
            "]);",
            "",
            f'export const PROVIDER_CATALOG_UPDATED_AT = "{CATALOG_UPDATED_AT}";',
            "",
        ]
    )


def main() -> None:
    entries = list_provider_entries()
    INDEX_PATH.write_text(render_index(entries))


if __name__ == "__main__":
    main()
