import {
  addResponseProvenanceToMessages,
  buildResponseProvenanceInstruction,
  createResponseProvenanceStreamFilter,
  getMessageContentWithResponseProvenance,
  getResponseProvenanceMarker,
  stripLeadingResponseProvenanceMarker,
} from "../../src/services/llm/messageProvenance";
import type { Message } from "../../src/types";

describe("LLM message provenance", () => {
  it("adds model identity only to model-facing assistant history", () => {
    const messages: Message[] = [
      {
        id: "user-1",
        role: "user",
        content: "Compare the answers.",
        model: null,
        provider: null,
        timestamp: "2026-07-20T10:00:00.000Z",
      },
      {
        id: "assistant-1",
        role: "assistant",
        content: "The first answer.",
        model: "claude-sonnet-5",
        provider: "anthropic",
        timestamp: "2026-07-20T10:00:01.000Z",
      },
    ];

    const annotated = addResponseProvenanceToMessages(messages);

    expect(annotated[0]).toBe(messages[0]);
    expect(annotated[1].content).toBe(
      "[Response generated by Anthropic using Claude Sonnet 5]\nThe first answer.",
    );
    expect(messages[1].content).toBe("The first answer.");
    expect(getMessageContentWithResponseProvenance(messages[1])).toBe(
      annotated[1].content,
    );
  });

  it("keeps Mistral thinking state and annotates only its answer text", () => {
    const annotated = addResponseProvenanceToMessages([
      {
        role: "assistant" as const,
        content: "The answer is 42.",
        model: "mistral-medium-3-5",
        provider: "mistral" as const,
        metadata: {
          providerState: {
            mistralAssistantContent: [
              {
                type: "thinking" as const,
                thinking: [{ type: "text" as const, text: "Calculate." }],
              },
              { type: "text" as const, text: "The answer is 42." },
            ],
          },
        },
      },
    ]);

    expect(
      annotated[0].metadata?.providerState?.mistralAssistantContent,
    ).toEqual([
      {
        type: "thinking",
        thinking: [{ type: "text", text: "Calculate." }],
      },
      {
        type: "text",
        text: "[Response generated by Mistral using Mistral Medium 3.5]\nThe answer is 42.",
      },
    ]);
  });

  it("describes both current and historical identities without encouraging output labels", () => {
    expect(
      buildResponseProvenanceInstruction({
        currentProvider: "openai",
        currentModel: "gpt-5.6-sol",
      }),
    ).toContain("current response is being generated by OpenAI using GPT-5.6 Sol");
    expect(
      buildResponseProvenanceInstruction({
        currentProvider: "openai",
        currentModel: "gpt-5.6-sol",
      }),
    ).toContain("Do not repeat the markers");
    expect(
      getResponseProvenanceMarker({ provider: null, model: null }),
    ).toBeNull();
  });

  it("removes every echoed provenance marker from complete and streamed replies", () => {
    expect(
      stripLeadingResponseProvenanceMarker(
        "[Response generated by Google using Gemini 3.5 Flash-Lite]\n" +
          "[Response generated by xAI using Grok 4.3]\n" +
          "The clean answer.",
      ),
    ).toBe("The clean answer.");

    const chunks: string[] = [];
    const filter = createResponseProvenanceStreamFilter((chunk) =>
      chunks.push(chunk),
    );
    filter.push("[Response gen");
    filter.push("erated by Google using Gemini 3.5 Flash-Lite]\n");
    filter.push("[Response generated by xAI using Grok 4.3]\nThe clean");
    filter.push(" answer.");
    filter.flush();

    expect(chunks.join("")).toBe("The clean answer.");
  });

  it("repairs contaminated history and never annotates it more than once", () => {
    const marker =
      "[Response generated by Google using Gemini 3.5 Flash-Lite]";
    const [annotated] = addResponseProvenanceToMessages([
      {
        role: "assistant" as const,
        content: `${marker}\n${marker}\nThe clean answer.`,
        model: "gemini-3.5-flash-lite",
        provider: "gemini" as const,
        metadata: {
          providerState: {
            geminiAssistantContent: [
              { text: `${marker}\n${marker}\nThe clean answer.` },
            ],
          },
        },
      },
    ]);

    expect(annotated.content).toBe(`${marker}\nThe clean answer.`);
    expect(
      annotated.metadata?.providerState?.geminiAssistantContent,
    ).toBeUndefined();
  });
});
