import { Platform } from "react-native";

const mockCompletion = jest.fn();
const mockRelease = jest.fn(async () => undefined);
const mockStopCompletion = jest.fn(async () => undefined);
const mockInitLlama = jest.fn(async () => ({
  completion: mockCompletion,
  release: mockRelease,
  stopCompletion: mockStopCompletion,
}));

jest.mock("llama.rn", () => ({ initLlama: mockInitLlama }));
jest.mock("../../src/services/localModelManager", () => ({
  getLocalModelInstallStatus: jest.fn(async () => ({
    installed: true,
    path: "/models/qwen.gguf",
    verified: true,
  })),
}));
jest.mock("../../src/services/localDeviceCapabilities", () => ({
  probeLocalDeviceCapabilities: jest.fn(),
  saveLocalModelBenchmarkResult: jest.fn(),
}));

import {
  LOCAL_LLM_IDLE_RELEASE_MS,
  releaseLocalLlmResources,
  sanitizeLocalResponseText,
  streamLocalChat,
} from "../../src/services/localLlm";

describe("local LLM", () => {
  beforeEach(async () => {
    await releaseLocalLlmResources();
    jest.clearAllMocks();
    mockCompletion.mockImplementation(
      async (
        _params: unknown,
        onToken?: (value: { token: string }) => void,
      ) => {
        onToken?.({ token: "Local " });
        onToken?.({ token: "reply." });
        return {
          content: "Local reply.",
          text: "Local reply.",
          interrupted: false,
          tokens_evaluated: 12,
          tokens_predicted: 3,
          timings: { predicted_per_second: 8 },
        };
      },
    );
  });

  afterAll(async () => {
    await releaseLocalLlmResources();
  });

  it("streams a response from the verified local model file", async () => {
    const onChunk = jest.fn();

    await expect(
      streamLocalChat({
        messages: [
          {
            id: "message-1",
            role: "user",
            content: "Hello",
            model: null,
            provider: null,
            timestamp: "2026-08-02T00:00:00.000Z",
          },
        ],
        modelId: "qwen3-0.6b-q8",
        assistantInstructions: "Be helpful.",
        responseLength: "brief",
        responseTone: "professional",
        language: "en",
        onChunk,
      }),
    ).resolves.toEqual(
      expect.objectContaining({
        fullText: "Local reply.",
        usage: expect.objectContaining({
          promptTokens: 12,
          completionTokens: 3,
          totalTokens: 15,
        }),
      }),
    );
    expect(mockInitLlama).toHaveBeenCalledWith(
      expect.objectContaining({ model: "/models/qwen.gguf" }),
    );
    expect(mockCompletion).toHaveBeenCalledWith(
      expect.objectContaining({ enable_thinking: false }),
      expect.any(Function),
    );
    expect(onChunk).toHaveBeenNthCalledWith(1, "Local ");
    expect(onChunk).toHaveBeenNthCalledWith(2, "reply.");
  });

  it("does not invite or expose an echoed hosted-response provenance marker", async () => {
    mockCompletion.mockImplementationOnce(
      async (
        _params: unknown,
        onToken?: (value: { token: string }) => void,
      ) => {
        onToken?.({ token: "[Response generated by " });
        onToken?.({ token: "provider using model]\n" });
        onToken?.({ token: "The local route works." });
        return {
          content:
            "[Response generated by provider using model]\nThe local route works.",
          text: "[Response generated by provider using model]\nThe local route works.",
          interrupted: false,
          tokens_evaluated: 12,
          tokens_predicted: 8,
          timings: { predicted_per_second: 8 },
        };
      },
    );
    const onChunk = jest.fn();

    const result = await streamLocalChat({
      messages: [],
      modelId: "qwen3-0.6b-q8",
      assistantInstructions: "Be helpful.",
      responseLength: "brief",
      responseTone: "professional",
      language: "en",
      onChunk,
    });

    expect(result.fullText).toBe("The local route works.");
    expect(onChunk.mock.calls.flat().join("")).toBe(
      "The local route works.",
    );
    expect(mockCompletion.mock.calls[0][0].messages[0].content).not.toContain(
      "[Response generated by provider using model]",
    );
  });

  it("uses an Android KV cache that can initialize without Flash Attention", async () => {
    const originalPlatform = Platform.OS;
    Object.defineProperty(Platform, "OS", {
      configurable: true,
      value: "android",
    });
    try {
      await streamLocalChat({
        messages: [],
        modelId: "qwen3-0.6b-q8",
        assistantInstructions: "Be helpful.",
        responseLength: "brief",
        responseTone: "professional",
        language: "en",
        onChunk: jest.fn(),
      });

      expect(mockInitLlama).toHaveBeenCalledWith(
        expect.objectContaining({
          cache_type_k: "f16",
          cache_type_v: "f16",
          flash_attn_type: "off",
        }),
      );
    } finally {
      await releaseLocalLlmResources();
      Object.defineProperty(Platform, "OS", {
        configurable: true,
        value: originalPlatform,
      });
    }
  });

  it("enables Qwen thinking only for the thorough local model", async () => {
    await streamLocalChat({
      messages: [],
      modelId: "qwen3-1.7b-q8",
      assistantInstructions: "Be helpful.",
      responseLength: "normal",
      responseTone: "professional",
      language: "en",
      onChunk: jest.fn(),
    });

    expect(mockCompletion).toHaveBeenCalledWith(
      expect.objectContaining({
        enable_thinking: true,
        n_predict: 1024,
        reasoning_format: "auto",
      }),
      expect.any(Function),
    );
  });

  it("releases a foreground-idle model context after a response", async () => {
    jest.useFakeTimers();
    try {
      await streamLocalChat({
        messages: [],
        modelId: "qwen3-0.6b-q8",
        assistantInstructions: "Be helpful.",
        responseLength: "brief",
        responseTone: "professional",
        language: "en",
        onChunk: jest.fn(),
      });

      expect(mockRelease).not.toHaveBeenCalled();
      await jest.advanceTimersByTimeAsync(LOCAL_LLM_IDLE_RELEASE_MS - 1);
      expect(mockRelease).not.toHaveBeenCalled();
      await jest.advanceTimersByTimeAsync(1);
      await Promise.resolve();
      expect(mockRelease).toHaveBeenCalledTimes(1);
    } finally {
      jest.useRealTimers();
    }
  });

  it("keeps Qwen reasoning and a generated English title out of a German answer", async () => {
    mockCompletion.mockImplementationOnce(
      async (
        _params: unknown,
        onToken?: (value: {
          content?: string;
          reasoning_content?: string;
          token: string;
        }) => void,
      ) => {
        onToken?.({
          token: "<think>English reasoning",
          content: "",
          reasoning_content: "English reasoning",
        });
        onToken?.({
          token: "</think>**Quantum Mechanics**",
          content: "**Quantum Mechanics**",
          reasoning_content: "English reasoning",
        });
        onToken?.({
          token: "\n\nDie Quanten",
          content: "**Quantum Mechanics**\n\nDie Quanten",
          reasoning_content: "English reasoning",
        });
        onToken?.({
          token: "mechanik ist faszinierend.",
          content:
            "**Quantum Mechanics**\n\nDie Quantenmechanik ist faszinierend.",
          reasoning_content: "English reasoning",
        });
        return {
          content:
            "<think>English reasoning</think>\n\n**Quantum Mechanics**\n\nDie Quantenmechanik ist faszinierend.",
          text: "<think>English reasoning</think>\n\n**Quantum Mechanics**\n\nDie Quantenmechanik ist faszinierend.",
          interrupted: false,
          tokens_evaluated: 14,
          tokens_predicted: 8,
          timings: { predicted_per_second: 7 },
        };
      },
    );
    const onChunk = jest.fn();

    const result = await streamLocalChat({
      messages: [],
      modelId: "qwen3-1.7b-q8",
      assistantInstructions: "Be helpful.",
      responseLength: "normal",
      responseTone: "professional",
      language: "de",
      onChunk,
    });

    expect(result.fullText).toBe("Die Quantenmechanik ist faszinierend.");
    expect(onChunk.mock.calls.flat().join("")).toBe(
      "Die Quantenmechanik ist faszinierend.",
    );
    expect(onChunk.mock.calls.flat().join("")).not.toContain("think");
    expect(onChunk.mock.calls.flat().join("")).not.toContain(
      "Quantum Mechanics",
    );
    const completionParams = mockCompletion.mock.calls[0][0];
    expect(completionParams.messages[0].content).toContain(
      "Antworte ausschließlich auf Deutsch",
    );
    expect(completionParams.messages[0].content).toContain(
      "keine englischen Überschriften",
    );
    expect(completionParams.messages[0].content).toContain(
      "Wenn die letzte Nachricht das Thema wechselt",
    );
    expect(result.termination).toEqual(
      expect.objectContaining({
        completionTokenLimit: 1024,
        limitReached: false,
      }),
    );
  });

  it("removes only standalone leading Markdown titles", () => {
    expect(
      sanitizeLocalResponseText(
        "**Quantum Mechanics**\n\nDie Quantenmechanik ist faszinierend.",
      ),
    ).toBe("Die Quantenmechanik ist faszinierend.");
    expect(
      sanitizeLocalResponseText("**Verschränkung** ist faszinierend."),
    ).toBe("Verschränkung ist faszinierend.");
    expect(
      sanitizeLocalResponseText("**Quantum Mechanics**", { streaming: true }),
    ).toBe("");
  });

  it("drops an unfinished private thinking block", () => {
    expect(sanitizeLocalResponseText("<think>Still reasoning in English")).toBe(
      "",
    );
  });
});
