import { StyleSheet } from "react-native";

import { fonts } from "../../theme/typography";

export const styles = StyleSheet.create({
  wrapper: {
    width: "100%",
  },
  wrapperUser: { alignItems: "stretch" },
  wrapperAssistant: { alignItems: "stretch" },
  messageRowTouchTarget: {
    width: "100%",
  },
  messageRow: {
    width: "100%",
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRadius: 6,
    borderWidth: 1,
    overflow: "hidden",
  },
  messageRowUser: {
    borderRightWidth: 3,
  },
  messageRowAssistant: {
    borderLeftWidth: 3,
  },
  messageRowSelectable: {
    width: "100%",
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 10,
  },
  modelChip: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 2,
  },
  providerIcon: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  roleLabel: {
    fontSize: 10,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    fontFamily: fonts.display,
  },
  modelLabel: {
    flexShrink: 1,
    fontSize: 11,
    fontFamily: fonts.body,
  },
  timestampLabel: {
    flexShrink: 0,
    fontSize: 10,
    letterSpacing: 0.2,
    fontFamily: fonts.mono,
  },
  content: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: fonts.body,
  },
  selectableContent: {
    width: "100%",
    padding: 0,
  },
  replyFailureCard: {
    alignSelf: "stretch",
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 7,
  },
  replyFailureHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  replyFailureTitle: {
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  replyFailureMessage: {
    fontSize: 12,
    lineHeight: 17,
    fontFamily: fonts.body,
  },
  replyFailureHint: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: fonts.body,
  },
  replyFailureAction: {
    alignSelf: "flex-start",
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  replyFailureActionText: {
    fontSize: 12,
    fontFamily: fonts.display,
  },
  noticeList: {
    gap: 8,
    marginTop: 10,
  },
  noticeCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  noticeIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  noticeCopy: {
    flex: 1,
    gap: 3,
  },
  noticeActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginTop: 3,
  },
  noticeAction: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 9,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  noticeActionText: {
    fontSize: 11,
    lineHeight: 15,
    fontFamily: fonts.display,
  },
  noticeLabel: {
    fontSize: 11,
    letterSpacing: 0.9,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  noticeText: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  noticeDetail: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: fonts.mono,
  },
  turnReceiptCard: {
    alignSelf: "stretch",
    marginTop: 12,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 0,
    gap: 0,
  },
  turnReceiptToggle: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  turnReceiptTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  turnReceiptTitle: {
    fontSize: 12,
    fontFamily: fonts.display,
  },
  turnReceiptToggleMeta: {
    flexShrink: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 5,
  },
  turnReceiptSummary: {
    flexShrink: 1,
    fontSize: 10,
    fontFamily: fonts.mono,
  },
  turnReceiptContent: {
    gap: 9,
    paddingTop: 8,
    paddingBottom: 10,
  },
  turnReceiptRow: {
    gap: 3,
  },
  turnReceiptLabel: {
    fontSize: 9,
    letterSpacing: 0.9,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  turnReceiptValue: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: fonts.body,
  },
  turnReceiptValueMono: {
    fontFamily: fonts.mono,
  },
  referenceCard: {
    alignSelf: "stretch",
    marginTop: 14,
    marginBottom: 4,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 0,
    gap: 0,
  },
  referenceToggle: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  referenceToggleTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  referenceToggleTitle: {
    fontSize: 12,
    fontFamily: fonts.display,
  },
  referenceToggleMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  referenceSourceCount: {
    fontSize: 10,
    fontFamily: fonts.mono,
  },
  referenceContent: {
    gap: 8,
    paddingTop: 8,
    paddingBottom: 10,
  },
  knowledgePolicyRow: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  knowledgePolicyText: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: fonts.bodyMedium,
  },
  referenceQuery: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  referenceSummary: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  referenceHeading: {
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  sourcesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  sourceChip: {
    maxWidth: "100%",
    minHeight: 44,
    alignItems: "flex-start",
    gap: 3,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  sourceLabel: {
    maxWidth: 180,
    fontSize: 12,
    fontFamily: fonts.body,
  },
  usageCard: {
    alignSelf: "stretch",
    marginTop: 10,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  usageText: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: fonts.mono,
  },
  branchIndicatorList: {
    marginTop: 12,
    gap: 6,
  },
  branchIndicator: {
    minHeight: 44,
    maxWidth: "100%",
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  branchIndicatorText: {
    flexShrink: 1,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: fonts.bodyMedium,
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 4,
    marginTop: 14,
    marginHorizontal: -12,
    marginBottom: -14,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  iconAction: {
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 0,
    alignItems: "center",
    justifyContent: "center",
  },
});
