import { StyleSheet } from "react-native";

import { fonts } from "../../theme/typography";

export const styles = StyleSheet.create({
  modalRoot: { flex: 1 },
  container: { flex: 1, flexDirection: "row" },
  drawer: {
    width: "100%",
    maxWidth: 520,
    height: "100%",
    borderRightWidth: 1,
  },
  backdrop: { flex: 1 },
  inlineActionOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: "flex-end",
    zIndex: 10,
  },
  inlineActionBackdrop: {
    ...StyleSheet.absoluteFill,
  },
  actionSheet: {
    maxHeight: "85%",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderBottomWidth: 0,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
  },
  actionSheetContent: {
    padding: 20,
    gap: 8,
  },
  actionSheetTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: fonts.display,
  },
  actionSheetHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  actionSheetHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  actionSheetMeta: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: fonts.mono,
  },
  actionSheetRow: {
    minHeight: 48,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  actionSheetDeleteRow: {
    marginTop: 4,
  },
  actionSheetRowText: {
    fontSize: 15,
    fontFamily: fonts.bodyMedium,
  },
  inlineRenameOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: "center",
    paddingHorizontal: 20,
    zIndex: 12,
  },
  inlineRenameBackdrop: {
    ...StyleSheet.absoluteFill,
  },
  renameCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 30,
    elevation: 10,
  },
  renameTitle: {
    fontSize: 20,
    lineHeight: 24,
    fontFamily: fonts.display,
  },
  renameHint: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  renameInput: {
    minHeight: 48,
    marginTop: 14,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: fonts.body,
  },
  renameActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 16,
  },
  renameAction: {
    minWidth: 92,
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  renameActionText: {
    fontSize: 13,
    fontFamily: fonts.display,
  },
  integrityOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 24,
    zIndex: 14,
  },
  integrityCard: {
    width: "100%",
    maxWidth: 720,
    maxHeight: "94%",
    borderRadius: 16,
    borderWidth: 1,
    padding: 20,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 30,
    elevation: 12,
  },
  integrityHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  integrityIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  integrityHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  integrityTitle: {
    fontSize: 20,
    lineHeight: 24,
    fontFamily: fonts.display,
  },
  integrityConversationTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  integrityClose: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  integrityDescription: {
    marginTop: 14,
    fontSize: 13,
    lineHeight: 20,
    fontFamily: fonts.body,
  },
  integrityStatus: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  integrityStatusText: {
    marginTop: 16,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.body,
  },
  integrityResult: {
    marginTop: 16,
    fontSize: 15,
    lineHeight: 21,
    fontFamily: fonts.bodyMedium,
  },
  integrityFindings: {
    marginTop: 12,
    maxHeight: 360,
  },
  integrityFindingsContent: {
    gap: 10,
    paddingBottom: 2,
  },
  integrityFinding: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 14,
    gap: 7,
  },
  integrityFindingLabel: {
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  integrityPreviewLabel: {
    marginTop: 3,
    fontSize: 12,
    fontFamily: fonts.bodyMedium,
  },
  integrityPreview: {
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  integrityManualReview: {
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.bodyMedium,
  },
  integrityActions: {
    marginTop: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 10,
  },
  integrityAction: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  integrityPrimaryAction: {
    minWidth: 150,
  },
  integrityActionText: {
    fontSize: 13,
    fontFamily: fonts.display,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  headerCopy: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  headerIconButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 20,
    lineHeight: 26,
    fontFamily: fonts.headline,
    fontWeight: "400",
    letterSpacing: -0.2,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.body,
  },
  newSessionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 4,
  },
  searchDock: {
    flexShrink: 0,
    borderTopWidth: 1,
    paddingTop: 10,
    paddingHorizontal: 18,
  },
  searchShell: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    paddingLeft: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    minHeight: 46,
    fontSize: 14,
    fontFamily: fonts.body,
  },
  searchClearButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  searchIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  listView: {
    flex: 1,
  },
  list: {
    paddingHorizontal: 0,
    paddingBottom: 24,
  },
  listEmpty: {
    flexGrow: 1,
  },
  sectionBand: {
    minHeight: 36,
    paddingVertical: 9,
    paddingLeft: 18,
    paddingRight: 8,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  sectionBandSeparated: {
    marginTop: 20,
  },
  sectionBandText: {
    flex: 1,
    fontFamily: fonts.display,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  sectionBandToggle: {
    width: 44,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    borderWidth: 0,
    borderRadius: 0,
    paddingHorizontal: 20,
    paddingVertical: 26,
    alignItems: "center",
    gap: 12,
    marginTop: 28,
    marginHorizontal: 18,
  },
  emptyStateCompact: {
    paddingVertical: 12,
    gap: 7,
    marginTop: 4,
  },
  emptyIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  emptyIconCompact: {
    width: 38,
    height: 38,
    borderRadius: 19,
  },
  emptyTitle: {
    fontSize: 18,
    textAlign: "center",
    fontFamily: fonts.display,
  },
  emptyTitleCompact: {
    fontSize: 16,
    lineHeight: 20,
  },
  emptyDescription: {
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    fontFamily: fonts.body,
  },
  emptyDescriptionCompact: {
    fontSize: 12,
    lineHeight: 17,
  },
  itemFrame: {
    borderRadius: 0,
    borderBottomWidth: 1,
    overflow: "hidden",
  },
  itemPressArea: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingLeft: 18,
    paddingRight: 4,
    paddingVertical: 10,
  },
  itemCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
    paddingTop: 2,
  },
  itemTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    minWidth: 0,
  },
  itemMetaRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    columnGap: 8,
    rowGap: 4,
  },
  itemTitle: {
    flexShrink: 1,
    fontSize: 15,
    lineHeight: 20,
    fontFamily: fonts.display,
  },
  itemMenuButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  itemMetaText: {
    fontSize: 11,
    lineHeight: 18,
    fontFamily: fonts.mono,
  },
  itemProviderMarks: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    columnGap: 6,
    rowGap: 4,
  },
  rootTagTarget: {
    alignSelf: "flex-start",
    maxWidth: "100%",
    minHeight: 44,
    marginVertical: -4,
    paddingVertical: 6,
    justifyContent: "center",
  },
  rootTag: {
    minHeight: 32,
    maxWidth: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    paddingLeft: 13,
    paddingRight: 10,
    paddingVertical: 5,
  },
  rootTagText: {
    flexShrink: 1,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: fonts.bodyMedium,
  },
  deleteAction: {
    width: 96,
    borderRadius: 0,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  deleteText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontFamily: fonts.display,
  },
});
