import { StyleSheet } from "react-native";

import { fonts } from "../../theme/typography";

export const styles = StyleSheet.create({
  container: { flex: 1, flexDirection: "row" },
  drawer: {
    width: "100%",
    maxWidth: 520,
    borderRightWidth: 1,
  },
  backdrop: { flex: 1 },
  inlineActionOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 16,
    zIndex: 10,
  },
  inlineActionBackdrop: {
    ...StyleSheet.absoluteFill,
  },
  actionSheet: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    gap: 10,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 30,
    elevation: 10,
  },
  actionSheetTitle: {
    fontSize: 18,
    lineHeight: 22,
    fontFamily: fonts.display,
  },
  actionSheetMeta: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.body,
    marginBottom: 4,
  },
  actionSheetRow: {
    minHeight: 46,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  actionSheetDeleteRow: {
    marginTop: 4,
  },
  actionSheetRowText: {
    fontSize: 14,
    fontFamily: fonts.display,
  },
  inlineRenameOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: "center",
    paddingHorizontal: 20,
    zIndex: 12,
  },
  inlineRenameBackdrop: {
    ...StyleSheet.absoluteFill,
  },
  renameCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 30,
    elevation: 10,
  },
  renameTitle: {
    fontSize: 20,
    lineHeight: 24,
    fontFamily: fonts.display,
  },
  renameHint: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.body,
  },
  renameInput: {
    minHeight: 48,
    marginTop: 14,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: fonts.body,
  },
  renameActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 16,
  },
  renameAction: {
    minWidth: 92,
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  renameActionText: {
    fontSize: 13,
    fontFamily: fonts.display,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingHorizontal: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  headerCopy: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  headerControlSpacer: {
    width: 44,
    height: 44,
  },
  title: {
    fontSize: 26,
    lineHeight: 32,
    fontFamily: fonts.headline,
    fontWeight: "400",
    letterSpacing: -0.25,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.body,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  newSession: {
    marginTop: 14,
    marginHorizontal: 18,
    marginBottom: 14,
    borderRadius: 12,
    minHeight: 48,
    paddingVertical: 12,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  newSessionText: {
    color: "#F4F8FF",
    fontSize: 15,
    fontFamily: fonts.display,
  },
  searchShell: {
    marginHorizontal: 18,
    marginBottom: 14,
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    paddingLeft: 14,
    paddingRight: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchInput: {
    flex: 1,
    minHeight: 42,
    fontSize: 14,
    fontFamily: fonts.body,
  },
  searchClearButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  list: {
    paddingHorizontal: 0,
    paddingBottom: 24,
  },
  emptyState: {
    borderWidth: 0,
    borderRadius: 0,
    paddingHorizontal: 20,
    paddingVertical: 26,
    alignItems: "center",
    gap: 12,
    marginTop: 28,
    marginHorizontal: 18,
  },
  emptyStateCompact: {
    paddingVertical: 12,
    gap: 7,
    marginTop: 4,
  },
  emptyIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  emptyIconCompact: {
    width: 38,
    height: 38,
    borderRadius: 19,
  },
  emptyTitle: {
    fontSize: 18,
    textAlign: "center",
    fontFamily: fonts.display,
  },
  emptyTitleCompact: {
    fontSize: 16,
    lineHeight: 20,
  },
  emptyDescription: {
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    fontFamily: fonts.body,
  },
  emptyDescriptionCompact: {
    fontSize: 12,
    lineHeight: 17,
  },
  itemFrame: {
    borderRadius: 0,
    borderBottomWidth: 1,
    overflow: "hidden",
  },
  item: {
    position: "relative",
    paddingHorizontal: 18,
    paddingVertical: 15,
    overflow: "hidden",
  },
  itemActiveRail: {
    position: "absolute",
    top: 12,
    bottom: 12,
    left: 0,
    width: 3,
    borderRadius: 2,
  },
  itemPressArea: {
    paddingRight: 54,
  },
  itemHeader: {
    marginBottom: 7,
  },
  itemTitleRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  itemTitle: {
    fontSize: 16,
    fontFamily: fonts.display,
  },
  itemMenuButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  itemMenuButtonFloating: {
    position: "absolute",
    top: 9,
    right: 14,
    zIndex: 2,
  },
  pinnedBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  pinnedBadgeText: {
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    fontFamily: fonts.mono,
  },
  itemMeta: {
    gap: 8,
  },
  itemModelList: {
    gap: 5,
  },
  itemModelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  itemModelText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.body,
  },
  itemFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  itemFooterMessages: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  itemFooterDot: {
    width: 3,
    height: 3,
    borderRadius: 2,
  },
  itemFooterText: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: fonts.body,
  },
  deleteAction: {
    width: 96,
    borderRadius: 0,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  deleteText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontFamily: fonts.display,
  },
});
