import {
  getProviderLabel,
  getProviderModelName,
} from "../../constants/models";
import type {
  GeminiAssistantContentPart,
  MessageMetadata,
  MistralAssistantContentChunk,
  Provider,
} from "../../types";

export const RESPONSE_PROVENANCE_MARKER_PREFIX = "[Response generated by ";

export function stripLeadingResponseProvenanceMarker(content: string) {
  const leadingWhitespaceLength = content.length - content.trimStart().length;
  const trimmedStart = content.slice(leadingWhitespaceLength);

  if (!trimmedStart.startsWith(RESPONSE_PROVENANCE_MARKER_PREFIX)) {
    return content;
  }

  const markerEnd = trimmedStart.indexOf("]");
  if (markerEnd < 0) {
    return content;
  }

  return trimmedStart.slice(markerEnd + 1).replace(/^\s+/, "");
}

export function createResponseProvenanceStreamFilter(
  onChunk: (text: string) => void,
) {
  let buffer = "";
  let resolved = false;

  const push = (text: string) => {
    if (!text) {
      return;
    }

    if (resolved) {
      onChunk(text);
      return;
    }

    buffer += text;
    const trimmedStart = buffer.trimStart();

    if (RESPONSE_PROVENANCE_MARKER_PREFIX.startsWith(trimmedStart)) {
      return;
    }

    if (trimmedStart.startsWith(RESPONSE_PROVENANCE_MARKER_PREFIX)) {
      if (!trimmedStart.includes("]")) {
        return;
      }

      const filtered = stripLeadingResponseProvenanceMarker(buffer);
      buffer = "";
      resolved = true;
      if (filtered) {
        onChunk(filtered);
      }
      return;
    }

    const unfiltered = buffer;
    buffer = "";
    resolved = true;
    onChunk(unfiltered);
  };

  const flush = () => {
    if (!resolved && buffer) {
      onChunk(buffer);
    }
    buffer = "";
    resolved = true;
  };

  return { flush, push };
}

interface ProvenanceMessage {
  role: "user" | "assistant";
  content: string;
  model?: string | null;
  provider?: Provider | null;
  metadata?: MessageMetadata;
}

export function getResponseProvenanceLabel(
  message: Pick<ProvenanceMessage, "model" | "provider">,
) {
  if (!message.provider || !message.model) {
    return null;
  }

  return `${getProviderLabel(message.provider)} using ${getProviderModelName(
    message.provider,
    message.model,
  )}`;
}

export function getResponseProvenanceMarker(
  message: Pick<ProvenanceMessage, "model" | "provider">,
) {
  const label = getResponseProvenanceLabel(message);
  return label ? `${RESPONSE_PROVENANCE_MARKER_PREFIX}${label}]` : null;
}

export function getMessageContentWithResponseProvenance(
  message: ProvenanceMessage,
) {
  if (message.role !== "assistant") {
    return message.content;
  }

  const marker = getResponseProvenanceMarker(message);

  if (!marker || message.content.startsWith(RESPONSE_PROVENANCE_MARKER_PREFIX)) {
    return message.content;
  }

  return `${marker}\n${message.content}`;
}

function addMarkerToMistralContent(
  content: MistralAssistantContentChunk[],
  marker: string,
) {
  let lastTextIndex = -1;

  content.forEach((chunk, index) => {
    if (chunk.type === "text") {
      lastTextIndex = index;
    }
  });

  if (lastTextIndex < 0) {
    return content;
  }

  return content.map((chunk, index) =>
    index === lastTextIndex && chunk.type === "text"
      ? { ...chunk, text: `${marker}\n${chunk.text}` }
      : chunk,
  );
}

function addMarkerToGeminiContent(
  content: GeminiAssistantContentPart[],
  marker: string,
) {
  // Thought signatures are opaque and must be replayed unmodified. Keep the
  // provenance marker in its own unsigned text part.
  return [{ text: `${marker}\n` }, ...content];
}

export function addResponseProvenanceToMessages<T extends ProvenanceMessage>(
  messages: T[],
  currentProvider?: Provider,
): T[] {
  return messages.map((message) => {
    if (message.role !== "assistant") {
      return message;
    }

    // Kimi K3 requires its complete prior assistant message to be replayed
    // unchanged. Its reasoning_content is restored later by the transport.
    if (
      currentProvider === "moonshot-ai-kimi" &&
      message.provider === currentProvider
    ) {
      return message;
    }

    const marker = getResponseProvenanceMarker(message);

    if (!marker || message.content.startsWith(RESPONSE_PROVENANCE_MARKER_PREFIX)) {
      return message;
    }

    const mistralAssistantContent =
      message.metadata?.providerState?.mistralAssistantContent;
    const geminiAssistantContent =
      message.metadata?.providerState?.geminiAssistantContent;

    return {
      ...message,
      content: getMessageContentWithResponseProvenance(message),
      ...(mistralAssistantContent || geminiAssistantContent
        ? {
            metadata: {
              ...message.metadata,
              providerState: {
                ...message.metadata?.providerState,
                ...(geminiAssistantContent
                  ? {
                      geminiAssistantContent: addMarkerToGeminiContent(
                        geminiAssistantContent,
                        marker,
                      ),
                    }
                  : {}),
                ...(mistralAssistantContent
                  ? {
                      mistralAssistantContent: addMarkerToMistralContent(
                        mistralAssistantContent,
                        marker,
                      ),
                    }
                  : {}),
              },
            },
          }
        : {}),
    };
  });
}

export function buildResponseProvenanceInstruction(params: {
  currentModel?: string;
  currentProvider?: Provider;
}) {
  const currentLabel = getResponseProvenanceLabel({
    model: params.currentModel,
    provider: params.currentProvider,
  });
  const currentIdentity = currentLabel
    ? `The current response is being generated by ${currentLabel}. `
    : "";

  return `${currentIdentity}Earlier assistant messages may begin with a [Response generated by provider using model] marker. Treat each marker as authoritative provenance for that specific response and keep those identities distinct. Never claim that you generated, wrote, or previously stated content attributed to another provider or model. Do not repeat the markers or announce your current identity unless the user asks.`;
}
