import {
  getProviderLabel,
  getProviderModelName,
} from "../../constants/models";
import type {
  GeminiAssistantContentPart,
  MessageMetadata,
  MistralAssistantContentChunk,
  Provider,
} from "../../types";

export const RESPONSE_PROVENANCE_MARKER_PREFIX = "[Response generated by ";

export function stripLeadingResponseProvenanceMarker(content: string) {
  let remaining = content;
  let removedMarker = false;

  while (true) {
    const trimmedStart = remaining.trimStart();
    if (!trimmedStart.startsWith(RESPONSE_PROVENANCE_MARKER_PREFIX)) {
      return removedMarker ? trimmedStart : content;
    }

    const markerEnd = trimmedStart.indexOf("]");
    if (markerEnd < 0) {
      return removedMarker ? remaining.trimStart() : content;
    }

    removedMarker = true;
    remaining = trimmedStart.slice(markerEnd + 1);
  }
}

export function createResponseProvenanceStreamFilter(
  onChunk: (text: string) => void,
) {
  let buffer = "";
  let resolved = false;
  let removedMarker = false;

  const push = (text: string) => {
    if (!text) {
      return;
    }

    if (resolved) {
      onChunk(text);
      return;
    }

    buffer += text;

    while (true) {
      const trimmedStart = buffer.trimStart();

      if (RESPONSE_PROVENANCE_MARKER_PREFIX.startsWith(trimmedStart)) {
        return;
      }

      if (trimmedStart.startsWith(RESPONSE_PROVENANCE_MARKER_PREFIX)) {
        const markerEnd = trimmedStart.indexOf("]");
        if (markerEnd < 0) {
          return;
        }

        removedMarker = true;
        buffer = trimmedStart.slice(markerEnd + 1);
        continue;
      }

      const unfiltered = removedMarker ? trimmedStart : buffer;
      buffer = "";
      resolved = true;
      if (unfiltered) {
        onChunk(unfiltered);
      }
      return;
    }
  };

  const flush = () => {
    if (!resolved && buffer) {
      const filtered = stripLeadingResponseProvenanceMarker(buffer);
      if (filtered) {
        onChunk(filtered);
      }
    }
    buffer = "";
    resolved = true;
  };

  return { flush, push };
}

interface ProvenanceMessage {
  role: "user" | "assistant";
  content: string;
  model?: string | null;
  provider?: Provider | null;
  metadata?: MessageMetadata;
}

export function getResponseProvenanceLabel(
  message: Pick<ProvenanceMessage, "model" | "provider">,
) {
  if (!message.provider || !message.model) {
    return null;
  }

  return `${getProviderLabel(message.provider)} using ${getProviderModelName(
    message.provider,
    message.model,
  )}`;
}

export function getResponseProvenanceMarker(
  message: Pick<ProvenanceMessage, "model" | "provider">,
) {
  const label = getResponseProvenanceLabel(message);
  return label ? `${RESPONSE_PROVENANCE_MARKER_PREFIX}${label}]` : null;
}

export function getMessageContentWithResponseProvenance(
  message: ProvenanceMessage,
) {
  if (message.role !== "assistant") {
    return message.content;
  }

  const marker = getResponseProvenanceMarker(message);
  const cleanContent = stripLeadingResponseProvenanceMarker(message.content);

  if (!marker) {
    return message.content;
  }

  return `${marker}\n${cleanContent}`;
}

function addMarkerToMistralContent(
  content: MistralAssistantContentChunk[],
  marker: string,
  cleanContent: string,
) {
  let lastTextIndex = -1;

  content.forEach((chunk, index) => {
    if (chunk.type === "text") {
      lastTextIndex = index;
    }
  });

  if (lastTextIndex < 0) {
    return content;
  }

  return content.map((chunk, index) =>
    index === lastTextIndex && chunk.type === "text"
      ? { ...chunk, text: `${marker}\n${cleanContent}` }
      : chunk,
  );
}

function getVisibleGeminiContent(content: GeminiAssistantContentPart[]) {
  return content
    .filter((part) => part.thought !== true)
    .map((part) => part.text ?? "")
    .join("");
}

function addMarkerToGeminiContent(
  content: GeminiAssistantContentPart[],
  marker: string,
  cleanContent: string,
) {
  // A Gemini response whose signed provider state already contains a marker
  // cannot be safely rewritten. Fall back to the clean text history instead
  // of replaying contaminated or invalid signed parts.
  if (getVisibleGeminiContent(content) !== cleanContent) {
    return null;
  }

  // Thought signatures are opaque and must be replayed unmodified. Keep the
  // provenance marker in its own unsigned text part.
  return [{ text: `${marker}\n` }, ...content];
}

export function addResponseProvenanceToMessages<T extends ProvenanceMessage>(
  messages: T[],
): T[] {
  return messages.map((message) => {
    if (message.role !== "assistant") {
      return message;
    }

    const marker = getResponseProvenanceMarker(message);
    const cleanContent = stripLeadingResponseProvenanceMarker(message.content);

    if (!marker) {
      return message;
    }

    const mistralAssistantContent =
      message.metadata?.providerState?.mistralAssistantContent;
    const geminiAssistantContent =
      message.metadata?.providerState?.geminiAssistantContent;
    const annotatedGeminiAssistantContent = geminiAssistantContent
      ? addMarkerToGeminiContent(
          geminiAssistantContent,
          marker,
          cleanContent,
        )
      : null;
    const providerState = message.metadata?.providerState;
    const {
      geminiAssistantContent: _geminiAssistantContent,
      mistralAssistantContent: _mistralAssistantContent,
      ...otherProviderState
    } = providerState ?? {};

    return {
      ...message,
      content: `${marker}\n${cleanContent}`,
      ...(mistralAssistantContent || geminiAssistantContent
        ? {
            metadata: {
              ...message.metadata,
              providerState: {
                ...otherProviderState,
                ...(annotatedGeminiAssistantContent
                  ? {
                      geminiAssistantContent: annotatedGeminiAssistantContent,
                    }
                  : {}),
                ...(mistralAssistantContent
                  ? {
                      mistralAssistantContent: addMarkerToMistralContent(
                        mistralAssistantContent,
                        marker,
                        cleanContent,
                      ),
                    }
                  : {}),
              },
            },
          }
        : {}),
    };
  });
}

export function buildResponseProvenanceInstruction(params: {
  currentModel?: string;
  currentProvider?: Provider;
}) {
  const currentLabel = getResponseProvenanceLabel({
    model: params.currentModel,
    provider: params.currentProvider,
  });
  const currentIdentity = currentLabel
    ? `The current response is being generated by ${currentLabel}. `
    : "";

  return `${currentIdentity}Earlier assistant messages may begin with a [Response generated by provider using model] marker. Treat each marker as authoritative provenance for that specific response and keep those identities distinct. Never claim that you generated, wrote, or previously stated content attributed to another provider or model. Do not repeat the markers or announce your current identity unless the user asks.`;
}
